remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Personal Blog
description: This is a personal blog to register my learning path
baseurl: "/blog"


